services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "0 0 3 * * *"
    environment:
      - TZ=Europe/Bucharest
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - WEBUI_PORT=9595
    volumes:
      - /data/container_data/qbitorrent:/config
      - /data/downloads:/downloads
      - /data/media/series:/series
      - /data/media/movies:/movies
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 9595:9595
    restart: always

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - JELLYFIN_PublishedServerUrl=192.168.0.53
    volumes:
      - /data/container_data/jellyfin:/config
      - /data/media/movies:/data/movies
      - /data/media/series:/data/tvshows
    ports:
      - 8096:8096
      - 1900:1900/udp
      - 7359:7359/udp
      - 8920:8920
    network_mode: host
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /data/container_data/sonarr:/config
      - /data:/host_data
    ports:
      - 8989:8989
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /data/container_data/radarr:/config
      - /data:/host_data
    ports:
      - 7878:7878
    restart: always

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /data/container_data/bazarr:/config
      - /data/media/movies:/movies
      - /data/media/series:/tv
    ports:
      - 6767:6767

  homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    ports:
      - 3000:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /data/container_data/homepage:/app/config
    restart: always
